### PR TITLE
feat(tsdf2d): remove use of weights from TSDF cost function

### PR DESCRIPTION
**Pull request by ajakhotia**
PR in support of https://github.com/carnegierobotics/knight/pull/2165

### CODE REVIEW

**Comment by catskul** [comment]
I suppose this should come out of draft

**Comment by ajakhotia** [comment]
@catskul @cdunkers: This is ready for review and merge.

**Comment by catskul** [comment]
Last time we discussed this I had been concerned that we were losing something valuable by removing the weights, specifically the encoding of certainty based on number of measurements/uncertainty of unexplored area. 

Can you mention the testing that's been done for this? i.e. has this been tested with a representative sample of problematic logs?

Is this tied directly to your recent EKF work?

**Comment by ajakhotia** [comment]
> Last time we discussed this I had been concerned that we were losing something valuable by removing the weights, specifically the encoding of certainty based on number of measurements/uncertainty of unexplored area.
> 
> Can you mention the testing that's been done for this? i.e. has this been tested with a representative sample of problematic logs?
> 
> Is this tied directly to your recent EKF work?

This is tied to EKF work. The presentation below documents the analysis that been done with this change + EKF.
https://docs.google.com/presentation/d/1DZtC3XnI6pUTqCPgmd-75w5LuEU24wuGNsPdNApznlw/edit#slide=id.p

I had to remove the weights so that the computed covariances would retain their geometric meaning. I couldn't think of a way to formulate the observation of a feature over time as a Gaussian process. If that problem can be solved, then it may make sense to re-introduce the weights and propagate the covariance of the said process to the pose estimates without corrupting them.

**Comment by brioja** [comment]
@cdunkers when this gets merged, I'll update the pointer on knight to point to master. Master is currently pointing to this branch.

**Review by cdunkers — APPROVED** [review]

**Pull request merged**
